{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-cachethq.fullname" . }}
  {{- if .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.serviceMonitor.namespace }}
  {{- end }}
  labels:
{{ include "prometheus-cachethq.labels" . | indent 4 }}
    {{- if .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml .Values.prometheus.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      {{- if .Values.prometheus.serviceMonitor.interval }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      {{- end }}
      {{ if .Values.prometheus.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{ if .Values.prometheus.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ .Values.prometheus.serviceMonitor.metricRelabelings }}
      {{- end }}
      {{ if .Values.prometheus.serviceMonitor.relabelings }}
      relabelings: {{ .Values.prometheus.serviceMonitor.relabelings }}
      {{- end }}
      scheme: {{ .Values.prometheus.serviceMonitor.scheme }}
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-cachethq.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}